name: pub_release
version: 6.0.1
homepage: https://github.com/bsutton/pub_release
description: Automates the release of a dart package to pub.dev including running dartfmt, creating a git tag, incrementing the packages version no. and pushing the package to pub.dev.
environment: 
  sdk: '>=2.12.0-259.12.beta <3.0.0'
dependencies: 
  dcli: ^0.50.0
  github: ^7.1.0-nullsafe.0
  meta: ^1.3.0
  mime: ^1.0.0
  pub_semver: ^2.0.0
  pubspec2: ^1.0.0
  settings_yaml: ^3.0.1
dev_dependencies: 
  lint: ^1.5.1
  pedantic: ^1.10.0
  test: ^1.16.2
executables: 
  pub_release: 
  github_release: 
  github_workflow_release: 
